version: '3'

services:
  # MySQL
  db:
    image: mysql:latest
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: RhoMethod
      # MYSQL_USER: attacker
      # MYSQL_PASSWORD: 0000
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./config/mysql/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
    restart: always
    
